### Author : BootLabsTech Pvt Ltd.
### Description: Schema YAML file for GKE Cluster Creation

# This should match the release tag
publishedVersion: '0.1.1'
publishedVersionMetadata:
  releaseNote: >-
    Initial release.
    # releaseTypes list is optional.
    # an existing vulnerability
    releaseTypes:
    - Feature
    - BugFix
    - Upgrade
    # If "recommended" is "true", users using older releases are encouraged
    # to update as soon as possible. This is useful if, for example, this release
    # fixes a critical issue.
    recommended: true
properties:
  vpc_name:
    inputType: textfield
    type: string # UI should render a text box
    description: name of the vpc # tool tip text
    title: "Vpc Name" # label in UI
    required: true # mandatory value
  vpc_cidr:
    inputType: textfield
    type: string # UI should render a text box
    description: cidr block for vpc. # tool tip text
    title: "Vpc Cidr" # label in UI
    required: true # mandatory value
  public_subnet1_cidr:
    inputType: textfield
    type: string # UI should render a text box
    description: cidr block for subnet # tool tip text
    title: "Public Subnet1 Cidr" # label in UI
    required: true # mandatory value
  subnet1_public :
    inputType: textfield
    type: string # UI should render a text box
    description: name of the subnet1 # tool tip text
    title: "Public Subnet1 Name" # label in UI
    required: true # mandatory value
  availability_zone1 :
    inputType: textfield
    type: string
    description: availability zone for the subnets
    title: "Availability Zone1"
    required: true
  availability_zone2 :
    inputType: textfield
    type: string
    description: availability zone for the subnets
    title: "Availability Zone2"
    required: true
   
  public_subnet2_cidr:
    inputType: textfield
    type: string
    description: subnet2 cidr block
    title: "Public Subnet2 Cidr"
    required: true
  subnet2_public:
    inputType: textfield
    type: string
    description: name of the subnet2
    title: "Public Subnet2 Name"
    required: true
  security_group_name:
    inputType: textfield
    type: string
    description: name of the security group
    title: "Security Group Name"
    required: true
  from_port:
    inputType: textfield
    type: number
    description: Enter the from port
    title: "From Port"
    required: true
  to_port:
    inputType: textfield
    type: number
    description: Enter the to port
    title: "To Port"
    required: true
  protocol:
    inputType: textfield
    type: string
    description: Enter the to protocol
    title: "Protocol"
    required: true

  instance_type:
    inputType: textfield
    type: string
    description: The type of instance to start
    title: "Instance Type"
    required: true
  volume_size:
    inputType: textfield
    type: number
    description: Whether to create an instance Size of the root volume in gigabytes
    title: "Volume Size"
    required: true
  name:
    inputType: textfield
    type: string
    description: Name to be used on EC2 instance created
    title: "Name"
    required: true
  key_name:
    inputType: textfield
    type: string
    description: Key name of the Key Pair to use for the instance
    title: "Key Name"
    required: true
  region:
    inputType: textfield
    type: string
    description: AWS Region the instance is launched in
    title: "Region"
    required: true 
  lb_name:
    inputType: textfield
    type: string
    description: values for lb name
    title: "LB Name"
    required: true
  lb_target_group_name:
    inputType: textfield
    type: string
    description: values for lb target group name
    title: "LB Target Group Name"
    required: true
  lb_protocol:
    inputType: textfield
    type: string
    description: values for lb protocol
    title: "LB Protocol"
    required: true
  lb_listener_port:
    inputType: textfield
    type: number
    description: values for listener port
    title: "LB Listener Port"
    required: true
  lb_listener_protocol:
    inputType: textfield
    type: string
    description: values for listener protocol
    title: "LB Listener Protocol"
    required: true 